export const isSignin = state => state.isSignin
export const loginname = state => state.loginname
export const avatarUrl = state => state.avatarUrl
export const id = state => state.id
export const score = state => state.score
export const accesstoken = state => state.accesstoken
export const theme = state => state.theme
export const isSaveDraft = state => state.isSaveDraft
export const isTopicTailOn = state => state.isTopicTailOn
export const topicTail = state => state.topicTail
