export const SET_ISSIGNIN = 'SET_ISSIGNIN'
export const SET_LOGINNAME = 'SET_LOGINNAME'
export const SET_AVATARURL = 'SET_AVATARURL'
export const SET_ID = 'SET_ID'
export const SET_SCORE = 'SET_SCORE'
export const SET_ACCESSTOKEN = 'SET_ACCESSTOKEN'
export const SET_THEME = 'SET_THEME'
